server:
  port: 65102

spring:
  application:
    name: service-gateway-2023
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    nacos:
      username: 'nacos'
      password: 'nacos'
      discovery:
        enabled: false
        server-addr: 111.230.1.219:8848
      config:
        enabled: true
        serverAddr: 111.230.1.219:8848
        username: 'nacos'
        password: 'nacos'
  config:
    import:
      - nacos:service-gateway-2023.properties?refreshEnabled=true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug