name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '8'
          architecture: x64
          targets: 'JAVA_8_HOME'

      - name: Setup JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64
          targets: 'JAVA_11_HOME'

      - name: Setup JDK 17
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '17'
          architecture: x64
          targets: 'JAVA_17_HOME;JAVA_HOME'

      - name: Install xmllint
        run: sudo apt-get install libxml2-utils

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build
        id: build
        run: |
          export use_docker_env=false
          pushd polaris-agent-build/bin
          echo $JAVA_HOME
          echo $JAVA_8_HOME
          bash ./build.sh ${{ steps.get_version.outputs.VERSION }}
          popd
          PACKAGE_NAME=$(ls | grep polaris-java-agent*.zip | sed -n '1p')
          echo ::set-output name=name::${PACKAGE_NAME}
      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.build.outputs.name }}
          asset_name: ${{ steps.build.outputs.name }}
          asset_content_type: application/gzip
