server:
  port: 65107

spring:
  application:
    name: service-provider-H
  cloud:
    nacos:
      username: 'nacos'
      password: 'UKt([$gc'
      discovery:
        enabled: false
        server-addr: 81.71.12.60:8848
      config:
        enabled: false
        serverAddr: 81.71.12.60:8848
        username: 'nacos'
        password: 'UKt([$gc'
  config:
    import:
      - nacos:service-provider-H.properties?refreshEnabled=true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info